- lib/common_components/add_custom_content_button.dart
- lib/screens/add_link/create_custom_add_link/create_custom_add_link.dart
- lib/screens/edit_persona/add_custom_field.dart
- lib/screens/edit_persona/edit_category_fields.dart
- lib/utils/at_enum.dart
Fix comment in issue [#353](https://github.com/atsign-foundation/apps/issues/353)
Update text
n/a
n/a
> fix: #353 correct word

- lib/utils/field_names.dart
Contains a fix for [Grey box and missing content on @jenijen's profile](https://github.com/atsign-foundation/apps/issues/470)
> Initialised customFields to blank array

- lib/common_components/confirmation_dialog.dart
- lib/common_components/custom_button.dart
- lib/utils/constants.dart
- lib/utils/theme.dart
Contains fix for:
- row turns white while reordering in dark mode.
- an outline appears on No button.
https://github.com/atsign-foundation/apps/issues/403
> Added canvasColor in darkTheme and highlightColor in custom_button

- .gitignore
- ios/Podfile.lock
- lib/main.dart
- lib/utils/constants.dart
- pubspec.lock
- pubspec.yaml
> Used flutter_dotenv

- lib/screens/options.dart
- lib/services/backend_service.dart
- lib/utils/colors.dart
- lib/utils/text_constants.dart
- delete atsign function extended for non primary atsigns
> delete non primary atsigns function added

- lib/screens/options.dart
- pubspec.lock
- pubspec.yaml
Fix [#353](https://github.com/atsign-foundation/at_widgets/issues/353) Onboarding Widget - QR Code scanner not working
> fix: QR Code scanner not working

- lib/screens/location/location_widget.dart
Added delete location icon for https://github.com/atsign-foundation/apps/issues/466#issue-1090174973 .
> Added delete location button

- CONTRIBUTING.md
- LICENSE
- README.md
- code_of_conduct.md
Modified README.md
Added CONTRIBUTING.md, code_of_conduct.md and LICENSE
[Community standards checklist on Insights](https://github.com/atsign-foundation/at_wavi_app/community) should all be ticked once merged.
@sarika01 the README.md still needs some work to explain the repo more to potential contributors.
Add community standards material
> Add community standards material

- pubspec.yaml
- Changed the SSH clone link to HTTPS clone link in `pubspec.yaml`
- created a branch and updated it.
> Fixed pub get issue for openforce contributors

- lib/common_components/custom_card.dart
- lib/common_components/custom_input_field.dart
- lib/screens/home/home.dart
- lib/services/common_functions.dart
- pubspec.lock
- pubspec.yaml
What I did
I disabled the search bar autocorrect and black space character input to solve the issue.
How I did it
To disable autocorrect, Flutter's TextField Widget provides autocorrect option which I toggled to false, along with the enableSuggestions option. Also, this doesn't work if the device's keyboard's autocorrect is on. So I set the keyboardType as visiblePassword (TextInputType.visiblePassword). It prevents the autocorrect in both the cases.
To prevent blank space, I used the string replaceAll method and replaced white spaces to empty character in the onChanged function parameter of the textfield
How to verify it
Type any user's atsign (for example barbaras). It previously autocorrected to Barbara's. Now it just displays barbaras, i.e. whatever we type. In case of blank spaces, …
> Fixes #164 (search bar autocorrect issue changes)

- lib/screens/edit_persona/html_editor_screen.dart
Contains fix for text not visible while typing https://github.com/atsign-foundation/apps/issues/305#issuecomment-1066730167.
> Added listview and removed shouldEnsureVisible from html editor

- lib/screens/home/home.dart
- pubspec.lock
- pubspec.yaml
> Added checkForUpdate function

- lib/desktop/screens/desktop_profile_basic_info/desktop_profile_add_custom_field/desktop_profile_add_custom_field_model.dart
Fix issue [#300](https://github.com/atsign-foundation/apps/issues/300)
> fix: for key not deleting when it has space at the end

- lib/desktop/screens/desktop_edit_profile/desktop_edit_profile_page.dart
- lib/desktop/utils/snackbar_utils.dart
Fix issue [#563](https://github.com/atsign-foundation/apps/issues/563)
I've added the confirm dialog when the user leaves screen without saving change
> fix: #563 - Reordered content keeps moving back

- lib/desktop/screens/desktop_my_profile/desktop_follow/widgets/desktop_user_widget.dart
- lib/desktop/screens/desktop_user_profile/desktop_profile_info_page.dart
- lib/desktop/utils/utils.dart
- lib/screens/home/home.dart
(https://github.com/atsign-foundation/apps/issues/5)
Fix issue [#5](https://github.com/atsign-foundation/apps/issues/5)
> fix: follow button appearing

- lib/model/user.dart
- lib/utils/at_enum.dart
- lib/utils/field_names.dart
(https://github.com/atsign-foundation/apps/issues/312)
Fix issue [#312](https://github.com/atsign-foundation/apps/issues/312)
> feat: add more presets to Social and Gaming sections

- CONTRIBUTING.md
- LICENSE
- README.md
- code_of_conduct.md
> chore: new branding

- lib/desktop/screens/desktop_appearance/desktop_appearance_page.dart
- lib/desktop/screens/desktop_edit_profile/desktop_edit_profile_page.dart
- lib/desktop/screens/desktop_edit_profile/desktop_profile_picture/desktop_profile_picture_page.dart
- lib/desktop/screens/desktop_my_profile/desktop_search_atsign/desktop_search_atsign_model.dart
- lib/desktop/screens/desktop_profile_basic_info/desktop_profile_basic_info_page.dart
- lib/desktop/screens/desktop_profile_basic_info/desktop_profile_media/desktop_profile_media_page.dart
- lib/services/backend_service.dart
- lib/services/theme_service.dart
- lib/view_models/user_provider.dart
- pubspec.lock
- pubspec.yaml
Update for task [#576](https://github.com/atsign-foundation/apps/issues/576)
> feat: error handling desktop

- lib/desktop/screens/desktop_login/desktop_onboarding_page.dart
- lib/desktop/screens/desktop_my_profile/desktop_settings/desktop_settings_page.dart
- Added delete function for desktop
- remove slide that reference free/discount.
> Feat: desktop delete atsign

- lib/view_models/user_preview.dart
- pubspec.yaml
Contains fix for [Deleted content re-appears](https://github.com/atsign-foundation/apps/issues/300).
> fix: fixed code to delete keys already created with trailing space

- lib/desktop/screens/desktop_profile_basic_info/widgets/desktop_empty_category_widget.dart
- lib/desktop/utils/strings.dart
- lib/screens/welcome.dart
- linux/flutter/generated_plugin_registrant.cc
- linux/flutter/generated_plugins.cmake
- macos/Flutter/GeneratedPluginRegistrant.swift
- macos/Podfile.lock
- pubspec.lock
- pubspec.yaml
- windows/flutter/generated_plugin_registrant.cc
- windows/flutter/generated_plugins.cmake
> chore: changed @wavi to atWavi

- lib/screens/home/home.dart
fix for the issue which was breaking the app when custom data was added to a profile.
> fix: null check issue
